source 'https://rubygems.org'

gem 'sequel'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-twitter-bootstrap', ">=2.3.1", :require => 'sinatra/twitter-bootstrap'
gem 'haml'
gem 'rack-flash3', :require => 'rack-flash'
gem 'json_pure', :require => 'json/pure'
gem 'deltacloud-client', '>=1.1.3'
gem 'sqlite3'
gem 'puma'
gem 'sidekiq'
gem 'rest-client'
gem 'json'
gem 'nokogiri'
gem 'pg'
gem 'will_paginate', '~> 3.0.0'
gem 'will_paginate-bootstrap'
gem 'pry'
gem 'slim'
gem 'net-ssh', :require => 'net/ssh'
gem 'net-scp', :require => 'net/scp'

gem 'deltacloud-core', '>=1.1.3', :require => 'deltacloud_rack'
